version: '3.9'

services:
  mongo:
    image: mongo:6.0
    container_name: annotation-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: annotation-server
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    command: npm run dev

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: annotation-client
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '5173:5173'
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 5173

volumes:
  mongo_data:
